name: Sync to srvmon

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to srvmon
        run: |
          git remote add srvmon https://hmtxj:${{ secrets.SYNC_TOKEN }}@github.com/hmtxj/srvmon.git
          git push srvmon main --force
